### ISSUE TITLE
Cancel all pending requests

### ISSUE THREAD

**Issue by pdgendt** [BlackMATov/curly.hpp#26]
Hi,

Is there a way to cancel/cleanup all pending requests? If you no longer call `curly_hpp::perform` from a main loop, all pending tasks are kept until the application quits.
This makes it complex if you want to be able to restart the main loop without having to keep track of all requests, especially when using promises.

**Comment by BlackMATov** [comment]
Hello!

I can make an API for extracting all pending requests, for example. It will allow to cancel them all or something else.

**Comment by BlackMATov** [comment]
Your wish has been granted :-)

**Comment by pdgendt** [comment]
Great work! Thanks!
